### ISSUE TITLE
Server editable for all user

### ISSUE THREAD

**Issue by beatbesmer** [cerb-plugins/cerberusweb.datacenter.servers#1]
If you grant access to the plugin to Users, they all can edit the server records. Why wont the servers have a owner, like the snippets? So i could add the server to a group and all group members can use the server records, zhe managers of zhe group can edit them.just ain suggestion. I don't like to grant write access gor all servers to all cerb users

**Comment by jstanden** [comment]
Hi Beat! There's nothing special about server records. You can ignore that plugin entirely and just create a custom record called 'Server' and enable record ownership. You could do the same with domains, and add a 'Record link' field back to 'Server'.

**Comment by beatbesmer** [comment]
Hi jeff. Thank you. This is why i closed it :)
